"""Simulator for the v2 (signature) scheme.

Instead of encrypting a TOTP code (v1), the device signs
"device_id|ts|lat|lng" with an ECDSA P-256 private key. The server only
stores the public key, so nothing on the server can forge a device.

The device id is not a manual label — it is the first 4 bytes of
SHA-256(pubkey X||Y) rendered as 8 hex chars, matching the firmware.

Usage:
    python python_generator_v2.py keygen   # once per device, prints the
                                           # public key PEM to register
    python python_generator_v2.py qr       # generate a signed QR code
    python python_generator_v2.py secrets  # print secrets.h for the ESP32
    python python_generator_v2.py pem <xy-hex>
                                            # convert an ATECC608 public key
                                            # (64-byte X||Y hex, as printed by
                                            # the hw_probe sketch) to the PEM
                                            # registered on the server

On the real device the same signature is produced by mbedtls (software)
or an ATECC608 secure element (hardware), both of which speak ECDSA P-256.
"""
import base64
import hashlib
import os
import sys
import time

import qrcode
from Crypto.PublicKey import ECC
from Crypto.Signature import DSS
from Crypto.Hash import SHA256

# base_url = "https://localproof.libmap.org"
base_url = "http://localhost:5005"

# Local key file to load (any label — actual device id is derived below).
key_label = "device"
device_lat = 48.188920
device_lng = 16.376279


def derive_device_id(public_key):
    xy = (public_key.pointQ.x.to_bytes(32, 'big') +
          public_key.pointQ.y.to_bytes(32, 'big'))
    return hashlib.sha256(xy).hexdigest()[:8]

KEY_DIR = "keys"


def key_path(label):
    return os.path.join(KEY_DIR, f"{label}_private.pem")


def generate_keypair(label):
    """Generate a P-256 keypair. The private key stays with the device
    (here: a local PEM file); the printed public key goes to the server."""
    os.makedirs(KEY_DIR, exist_ok=True)
    path = key_path(label)
    if os.path.exists(path):
        raise SystemExit(f"Refusing to overwrite existing key: {path}")

    key = ECC.generate(curve='P-256')
    with open(path, 'wt') as f:
        f.write(key.export_key(format='PEM'))
    print(f"Private key saved to '{path}' (keep it on the device, never commit it)")
    print(f"\nDerived device id: {derive_device_id(key.public_key())}")
    print("\nPublic key to register on the server:\n")
    print(key.public_key().export_key(format='PEM'))


def print_arduino_secrets(label):
    """Print a ready-to-paste secrets.h for the software-key firmware path."""
    with open(key_path(label), 'rt') as f:
        pem = f.read().strip()
    print('// Generated by python_generator_v2.py — do not commit.')
    print('#define DEVICE_PRIVATE_KEY_PEM \\')
    lines = pem.splitlines()
    for i, line in enumerate(lines):
        cont = ' \\' if i < len(lines) - 1 else ''
        print(f'  "{line}\\n"{cont}')


def pem_from_xy_hex(xy_hex):
    """Convert an ATECC608 slot public key (64-byte X||Y hex) to PEM and
    print the derived device id."""
    xy = bytes.fromhex(xy_hex)
    if len(xy) != 64:
        raise SystemExit(f"Expected 64 bytes (128 hex chars), got {len(xy)}")
    key = ECC.construct(curve='P-256',
                        point_x=int.from_bytes(xy[:32], 'big'),
                        point_y=int.from_bytes(xy[32:], 'big'))
    print(f"Derived device id: {derive_device_id(key)}\n")
    print(key.export_key(format='PEM'))


def sign_payload(private_key, device_id, ts, lat, lng):
    """Sign 'device_id|ts|lat|lng', return (payload_b64, sig_b64).

    The payload string is signed exactly as transmitted, so the server can
    verify without re-formatting floats.
    """
    payload = f"{ts}|{lat:.6f}|{lng:.6f}"
    message = f"{device_id}|{payload}".encode('utf-8')
    signature = DSS.new(private_key, 'fips-186-3').sign(SHA256.new(message))
    return (
        base64.urlsafe_b64encode(payload.encode('utf-8')).decode('ascii'),
        base64.urlsafe_b64encode(signature).decode('ascii'),
    )


def generate_signed_qr(label, lat, lng):
    with open(key_path(label), 'rt') as f:
        private_key = ECC.import_key(f.read())

    device_id = derive_device_id(private_key.public_key())
    ts = int(time.time())
    payload_b64, sig_b64 = sign_payload(private_key, device_id, ts, lat, lng)
    validation_url = f"{base_url}/v2/{device_id}/{payload_b64}/{sig_b64}"

    print(f"Device id: {device_id}")
    print(f"Signed at ts={ts}")
    print(f"Validation URL: {validation_url}")

    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=10, border=4)
    qr.add_data(validation_url)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    os.makedirs("static", exist_ok=True)
    img_path = f"static/{device_id}_signed_qr.png"
    img.save(img_path)
    print(f"QR code saved as '{img_path}' (version {qr.version})")


if __name__ == "__main__":
    command = sys.argv[1] if len(sys.argv) > 1 else 'qr'
    if command == 'keygen':
        generate_keypair(key_label)
    elif command == 'qr':
        generate_signed_qr(key_label, device_lat, device_lng)
    elif command == 'secrets':
        print_arduino_secrets(key_label)
    elif command == 'pem':
        if len(sys.argv) < 3:
            raise SystemExit("Usage: python python_generator_v2.py pem <xy-hex>")
        pem_from_xy_hex(sys.argv[2])
    else:
        raise SystemExit(f"Unknown command '{command}' (use 'keygen', 'qr', 'secrets' or 'pem')")
